name: neonbot
description: Discord bot for scheduling Valorant premier events.
version: 0.0.1
repository: https://github.com/nineonefive/neonbot

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  chaleno: ^0.0.8
  collection: ^1.18.0
  event_bus: ^2.0.0
  http: ^1.2.1
  intl: ^0.19.0
  logging: ^1.2.0
  nyxx: ^6.2.0
  nyxx_commands: ^6.0.2
  puppeteer: ^3.9.0
  sqlite3: ^2.4.1+1
  timezone: ^0.9.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
